### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by mchlrv** [koenhendriks/ha-eplucon#1]
**Version**: 1.0

After adding the integration and adding my API key I encounter the following error

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eplucon/__init__.py", line 41, in async_update_data
    realtime_info = await client.get_realtime_info(device_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eplucon/eplucon_api/eplucon_client.py", line 54, in get_realtime_info
    common_info = CommonInfoDTO(**data['data']['common'])
```

**Comment by koenhendriks** [comment]
At first glance there doesn't seem to be any realtime information for the device you have connected in Eplucon.

Could you tell me what devices you have? I'll try to put some more debugging logs in for version 1.1.0

**Comment by mchlrv** [comment]
I've got a th-TOUCH connected. Whenever I login to the Eplucon portal I can see the information about this device.

**Comment by koenhendriks** [comment]
I've released [1.1.0 Beta](https://github.com/koenhendriks/ha-eplucon/releases/tag/1.1.0-beta) could you try this and send me the output of the debug?

**Comment by mchlrv** [comment]
Please find the log attached.
[home-assistant_eplucon_2024-09-03T06-53-50.650Z.log](https://github.com/user-attachments/files/16844690/home-assistant_eplucon_2024-09-03T06-53-50.650Z.log)

**Comment by koenhendriks** [comment]
Alright so from the log it seems that you actually have 2 devices linked in your Eplucon and 1 is working fine (the heat_pump) and another one called `zone_controller` is not working.

I'm not sure what devices a `zone_controller` is, but the API does not allow your account to retrieve realtime information from the `zone_controller` which is why the integration is crashing. 

I think I should be able to extend the error handling a bit and remove devices that we get API errors from or maybe just support devices with the type `heat_pump` for now.

**Comment by mchlrv** [comment]
The `zone_controller` is a [Touch M-9-R](https://tech-controllers.com/p/eu-m-9-r) which controls my thermostats. The `heat_pump` is a rebranded Touch M-9-R (a.k.a. TH-Touch) which only controls my heat pump and not the thermostats.

**Comment by mchlrv** [comment]
I can give you access to my API of that helps.

**Comment by koenhendriks** [comment]
If you could send it to me that would be great! 

[info@koenhendriks.com](mailto:info@koenhendriks.com
)

**Comment by koenhendriks** [comment]
Please update to [v1.2.1](https://github.com/koenhendriks/ha-eplucon/releases/1.2.1) this should be fixed now.
