### ISSUE TITLE
Add Dropdown for Base URL for German Customers

### ISSUE THREAD

**Issue by travismarius** [koenhendriks/ha-eplucon#10]
First of all: Many Thanks for creating that HACS Integration. I own the EcoForest Heatpump with Eplicon TH-Touch since july 24 and I´m so glad you´ve developed that Integration!

I´ve just set it up and got the problem, that I´m from Germany and basically using https://portaal.eplucon.de/e-control/heatpump as Website Access and also another URL for https://portaal.eplucon.de/api/v2

I´ve changed the BASE_URL = "https://portaal.eplucon.nl/api/v2" in Line11 in eplucon_client.py, after that restart of homeassistant and then i was able to add the integration with my API Key. Would be great if you consider to add this as dropdown in your integration. (see screenshots)

Again, many thanks. I´ll start testing and using it since the heating season has finally started :)

regards,
travis
![image](https://github.com/user-attachments/assets/b2837461-8d68-4eb1-9cce-0515e92df801)

**Comment by koenhendriks** [comment]
I've created the option to manual set or update the API endpoint. Thanks for the suggestion!
