### ISSUE TITLE
update dacite dependency

### ISSUE THREAD

**Issue by christianvaes** [koenhendriks/ha-eplucon#2]
Hi,

Every time I install an update of the Eplucon integration(using HACS) the Roborock integration stops working with the following error:

`File "/usr/local/lib/python3.12/site-packages/roborock/containers.py", line 112, in from_dict
    raise RoborockException("It seems like you have an outdated version of dacite.") from err
roborock.exceptions.RoborockException: It seems like you have an outdated version of dacite.`

This seems to be caused by an old version of the python package 'dacite' used in this integration which overrides the default one of home assistant. Is there a possibility to update the dacite package used in this integration to the latest version?

**Comment by koenhendriks** [comment]
Hmm I did not specify any version in my `requirements.txt` thinking this would mean the latest stable release., but I guess that's not how python dependencies are managed. 

I'll take a look if I can enforce the latest `dacite` version and see if everything is still stable. That should fix this issue (assuming that the Roborock extension is actually on the latest).

**Comment by koenhendriks** [comment]
I've tried updating it to be `dacite==1.8.1` but I don't think that's going to fix the issue as I get the message `Requirement already satisfied: dacite==1.8.1` 

Maybe the issue is with Roborock?

**Comment by christianvaes** [comment]
I thought that as well first, but then found https://github.com/home-assistant/core/issues/122411 this mentions that another integration(Govee) downgrades the dacite dependency and causes the issue. After they removed that integration the roborock integration start to work. But since I don't have this govee integration I searched which integration used the dacite dependency aswell. This turned out to be eplucon integration. After that I tried to fix it. One weird thing is that when I try to click "download again" for the eplucon integration detail page in hacs and restart home assistant both integration start to work again and the error is gone. However after some restarts it comes up again. That's why I thought it's related to the dependencies of Eplucon which override the default dacite from Home assistant. For that reason I made this issue as it looks like that eplucon integration is impacting the dacite dependency (sometimes) somehow.

Do you have another idea based on above explanation?

**Comment by koenhendriks** [comment]
I'll try `dacite>=1.8.1,<2.0.0` for the next release. That should cover any future update until the next major release.

**Comment by koenhendriks** [comment]
I've released [v1.2.2](https://github.com/koenhendriks/ha-eplucon/releases/tag/1.2.2) with this update. Let me know if this fixes it. If not, I'm afraid there is not much more I can do on the problem.

**Comment by christianvaes** [comment]
I installed the new version, atleast the initial restart was without issues(previously this went wrong many times). Will keep an eye on this and report back.

**Comment by koenhendriks** [comment]
Hmm that's weird. Maybe I can import dacite through home assistant (just like aiohttp)

**Comment by christianvaes** [comment]
Do you have an updated version with this change? I would like to test if needed.

**Comment by koenhendriks** [comment]
I've been unable to load `dacite` in any other way.  As far as I can tell Homeassistant also loads dacite externally.

Is there anyway to pinpoint what version of dacite homeassistant is using? 

If I search around the web for `dacite` and `homeassistant` I only get Roborock related issues... are you sure it's related to this component and homeassistant and not RoboRock?

**Comment by christianvaes** [comment]
Hi @koenhendriks I agree, I will create an issue at roborock integration to mention this and see if they have an option to fix this.
