### ISSUE TITLE
Showing in the setup and device list items which is stated in the logging not supported yet.

### ISSUE THREAD

**Issue by bios2bios** [koenhendriks/ha-eplucon#3]
It shows an additional device while in the loggin it states not supported yet. I would expect then it would not be shown in the setup and in this screen as well.

The additional items are the tech controllers. And when it is shown i would expect to have all shown as i have 2 and not 1

![image](https://github.com/user-attachments/assets/581df457-7837-4d9b-b057-5bd2e492edfa)

**Comment by koenhendriks** [comment]
Hmm.. could this be added from an earlier version before I added the 'support' feature? 

I can't really replicate this as I don't have the tech controllers, just the `heat_pump`.

**Comment by bios2bios** [comment]
I dont have the issue anymore as i moved my tech controllers to another service provider.
