### ISSUE TITLE
Unit of pumps are not correct it is not RPM but %

### ISSUE THREAD

**Issue by bios2bios** [koenhendriks/ha-eplucon#4]
The unit of the sensors for the pumps are incorrect. The compressor is indeed RMP the brine and circulation %.

![image](https://github.com/user-attachments/assets/594b8ad4-ae88-475e-9766-3f1283ae6784)

![image](https://github.com/user-attachments/assets/4438716b-8fde-4052-9fc7-c606deec9ee1)

![image](https://github.com/user-attachments/assets/5d68aae4-eebb-4243-8b60-c35320a03104)

**Comment by koenhendriks** [comment]
Seems the Eplucon website and API servers are down so can't test right now. Will update soon. Thanks for the report.

**Comment by koenhendriks** [comment]
[v1.2.2](https://github.com/koenhendriks/ha-eplucon/releases/tag/1.2.2) was just released and fixes the units.
