### ISSUE TITLE
Unavailibility of values which shows in history graphs (unwanted)

### ISSUE THREAD

**Issue by bios2bios** [koenhendriks/ha-eplucon#6]
De API is each night not available for a minute or 15 which results in he history and graphs a moment where the value is 0. Is it possible to keep the value as i was last known. Or that the service can have a time out for a configured periode.

Picture from entity provided by the integration
![image](https://github.com/user-attachments/assets/38c8bde1-e5f8-4930-becf-7eb8654a893f)
![image](https://github.com/user-attachments/assets/a71c0c6b-7554-4ed1-8a9c-720f407bf71c)

Picture from my multiscrape which pauses for a minute during service window of API provider to keep last value. In this picture the last value is used instead of having a gap to 0. This way the range of the y as is more accurate as it does not need to show from 0 to 60.
![image](https://github.com/user-attachments/assets/72a92a69-00ac-4372-938c-0f195184932d)
![image](https://github.com/user-attachments/assets/ab4b21ae-d0be-4ebe-af84-cff83efe9528)

**Comment by koenhendriks** [comment]
If you received a value of `0`that means that Eplucon has send a `0` from the API. 

If there is an API error (invalid response or any HTTP status errors) the coordinator doesn't send an update (see [the coordinator.py](https://github.com/koenhendriks/ha-eplucon/blob/main/custom_components/eplucon/coordinator.py#L70-L80)) 

I'm having some trouble with the API myself, I have not received a valid response since the 6th of September 

![image](https://github.com/user-attachments/assets/48db0394-fa76-4a25-9932-8c9a8e3e4044)

It's not that the integration is working correctly, but that the API has been sending the same unchanged data for the last month. 

I've send an email to Eplucon about this last monday (23th of September) but have yet to receive an answer.

**Comment by bios2bios** [comment]
> If you received a value of `0`that means that Eplucon has send a `0` from the API.
> 
> If there is an API error (invalid response or any HTTP status errors) the coordinator doesn't send an update (see [the coordinator.py](https://github.com/koenhendriks/ha-eplucon/blob/main/custom_components/eplucon/coordinator.py#L70-L80))
> 
> I'm having some trouble with the API myself, I have not received a valid response since the 2nd of September
> 
> ![image](https://private-user-images.githubusercontent.com/4124579/371665796-48db0394-fa76-4a25-9932-8c9a8e3e4044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NjgwNTEsIm5iZiI6MTcyNzQ2Nzc1MSwicGF0aCI6Ii80MTI0NTc5LzM3MTY2NTc5Ni00OGRiMDM5NC1mYTc2LTRhMjUtOTkzMi04YzlhOGUzZTQwNDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjdUMjAwOTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjc0NzRkOTI2ZWU1YmM2NDJlNjE5NDNiZmRkNDgxMGZhOWRiNjc0NzJmMGYwNjk0NTg5ZTVhNTlkNDhmZDQ0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.D4qa2yDfVcNY4p0vJui_HqRU4iYasHsttO2S7zDJTlE)
> 
> It's not that the integration is working incorrectly, but that the API has been sending the same unchanged data for the last month.
> 
> I've send an email to Eplucon about this last monday (23th of September) but have yet to receive an answer.

I had some issues as well using the integration. But i have no issues with the API using the multiscrape integration except for a short momen to the 22nd. 
![image](https://github.com/user-attachments/assets/19db70f9-aef4-4d44-97a4-e438dc83f2e7)

Based on your information you think it will jus provide a value of 0 at around 03:45. I have seen this for all attributes as part of my muliscrape config as well. To prevent the 0 as an outlier and keep the good last known value i disable scraping it for 15 to 30 minutes.

**Comment by koenhendriks** [comment]
I'm not really up for rewriting the sensor update method to ignore certain differences between a current and new value.

I'm open for a PR.
