### ISSUE TITLE
No statistics for attributes like Brine Circulation Pump

### ISSUE THREAD

**Issue by bios2bios** [koenhendriks/ha-eplucon#7]
When opening the history to show the graph, it does not show history.

![image](https://github.com/user-attachments/assets/8521d9a2-118d-4220-a4c9-d75f02ca3c44)

I would like to have for all attributes the historical informaiton so it can be shown in diagram as below
![image](https://github.com/user-attachments/assets/94703938-134e-4bbd-8b3e-fbfcf2da7b30)

**Comment by koenhendriks** [comment]
Do you receive this information from the actual API if you do a manual call? Otherwise it might be because the Eplucon API isn't working correctly at the moment (see https://github.com/koenhendriks/ha-eplucon/issues/6#issuecomment-2379971716)

**Comment by bios2bios** [comment]
> Do you receive this information from the actual API if you do a manual call? Otherwise it might be because the Eplucon API isn't working correctly at the moment (see [#6 (comment)](https://github.com/koenhendriks/ha-eplucon/issues/6#issuecomment-2379971716))

I receive it for all the other attributes as part of the integration. And i receive from the API using my multiscape setup

**Comment by bios2bios** [comment]
> > Do you receive this information from the actual API if you do a manual call? Otherwise it might be because the Eplucon API isn't working correctly at the moment (see [#6 (comment)](https://github.com/koenhendriks/ha-eplucon/issues/6#issuecomment-2379971716))
> 
> I receive it for all the other attributes as part of the integration. And i receive from the API using my multiscape setup

I double checked it with postman. it returns currently 0.0 which is correct as it is not running at this moment.

` "sg4": "",
            "warmwater": 0,
            "brine_circulation_pump": "0.0",
            "production_circulation_pump": "0.0",
            "act_vent_rpm": "0.0",
            "alarm_active": false,`

**Comment by koenhendriks** [comment]
I've checked on the latest release and I can see the history data:

![image](https://github.com/user-attachments/assets/a9bad388-70c6-4faa-b587-a86d2537b7a3)

**Comment by koenhendriks** [comment]
Please update to [1.3.0](https://github.com/koenhendriks/ha-eplucon/releases/tag/1.3.0) and re-open this issue if you still encounter this.
