### ISSUE TITLE
Number of Starts (and other attributes) looks not like a number when showing history

### ISSUE THREAD

**Issue by bios2bios** [koenhendriks/ha-eplucon#8]
As is shown by the sensor of the integration
![image](https://github.com/user-attachments/assets/c1c7d345-befc-4ea5-87b6-c9ef8d3ba518)

As it is shown by my user defined sensor via Multiscrape 
![image](https://github.com/user-attachments/assets/2c856f2d-92af-4954-a746-8e9de67ed7a6)

Probably adding just a "unit_of_measurement: counter" is sufficient. for the number of starts 

Also other attributes which are a number show it as a bar
Operation Mode
Position Expansion Ventil (which by the way is also a percentage and the unit is not shown in the integration)
SPF

**Comment by koenhendriks** [comment]
Please update to [1.3.0](https://github.com/koenhendriks/ha-eplucon/releases/tag/1.3.0)
