### ISSUE TITLE
Add friendly name of numerical state as an attribute

### ISSUE THREAD

**Issue by bios2bios** [koenhendriks/ha-eplucon#9]
Some of the attributes have a numerical value which corresponds with a certain state or model.

Operation Mode has a range from 1-5) {1: 'Koeling', 2: 'Verwarming', 3:'Auto th-TOUCH', 4:'Auto Wp', 5: 'Haard'}
Can you add it to the sensor as an attribute

The example below shows it the way around, however the most important is to have both values available one as the state and the other as an attribute. 
![image](https://github.com/user-attachments/assets/c084b681-add4-4dc1-a470-6cf21feff8c1)

**Comment by koenhendriks** [comment]
I've added the `operation_mode_text` sensor as `enum` in the following release:

![image](https://github.com/user-attachments/assets/7625c9bc-99c6-4ddd-b2b9-d5d2b9a53aea)

 Might need to look into translations for this as now the value's are hardcoded in Dutch.

**Comment by koenhendriks** [comment]
Please update to [1.3.0](https://github.com/koenhendriks/ha-eplucon/releases/tag/1.3.0)
